services:
    qdrant:
        volumes:
            - './qdrant_storage:/qdrant/storage'
        image: qdrant/qdrant
        ports:
            - 6333:6333
            - 6334:6334

# Загрузка только одной модели yxchia/multilingual-e5-base
    ollama:
        build:
            dockerfile: DOCKERFILE
        #command: 
        volumes:
             - './ollama:/root/.oolama' 
        ports:
              - 11434:11434     